### PR TITLE
factor XI: log to stdout

### PR DESCRIPTION
**Pull request by jkt628**
https://github.com/adobe-community/issues-ethos/issues/3791

### CODE REVIEW

**Comment by MikeWillCook** [comment]
@jkt628, should all those references to "stderr" and "error" be "/dev/stderr" like the stdout?

**Comment by jkt628** [comment]
interesting imbalance: error_log has a standard keyword 'stderr' but access_log lacks 'stdout'.  the bare word is preferred.

**Comment by MikeWillCook** [comment]
Ah, so should the `error` mentions be `stderr` then?

**Comment by MikeWillCook** [comment]
👍

**Pull request closed without merging**
