### PR TITLE
support large request with CLIENT_MAX_BODY_SIZE

### PR DESCRIPTION
**Pull request by jkt628**
default to 10M

### CODE REVIEW

**Comment by jkt628** [comment]
https://git.corp.adobe.com/adobe-platform/sos/issues/530

**Comment by MikeWillCook** [comment]
@jkt628, did you mean to change the references from $ssl to $temp in marathon_api_ssl, as $temp was local in another function?

**Comment by jkt628** [comment]
good catch, i had it in some previous version but lost it again along the way

**Comment by MikeWillCook** [comment]
👍

**Pull request merged**
