### PR TITLE
apigateway.gw.* gets 502 'Bad Gateway'

### PR DESCRIPTION
**Pull request by jkt628**

### CODE REVIEW

**Comment by MikeWillCook** [comment]
So how does this behave if the marathon discovery script is not running?

**Comment by jkt628** [comment]
http://apigateway.gw.* will work, https://apigateway.gw.* will fail with 502.  should i add a static section for https?

**Comment by MikeWillCook** [comment]
If we have an http link working I guess an https working (if SSL is enabled) would be good for consistency...

**Comment by MikeWillCook** [comment]
👍

**Pull request closed without merging**
