### PR TITLE
add /metrics for Prometheus using nginx-vts-exporter and nginx-module…

### PR DESCRIPTION
**Pull request by jkt628**
…-vts

### CODE REVIEW

**Comment by jkt628** [comment]
https://github.com/adobe-community/issues-ethos/issues/2911

**Comment by MikeWillCook** [comment]
👍 Initial testing with the 0.6.5 image you referred me to earlier is looking good so far...

**Comment by MikeWillCook** [comment]
@jkt628, should we have the apigateway health check interrogate the /metrics endpoint to verify that process is running and healthy?

**Comment by jkt628** [comment]
1. apigateway health-check doesn't actually query health of anything.  why should this be different?
1. nginx-vts-exporter is just a simple translator from JSON to Prometheus and is unlikely to fail.  in spite of that i put it in a restart loop if it ever does.
1. if Prometheus has alerts we should use that to indicate a problem.

**Pull request merged**
